# Generated by Django 4.0.6 on 2022-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('edu', models.CharField(max_length=1000)),
                ('exp', models.CharField(max_length=1000)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('skill4', models.CharField(max_length=100)),
            ],
        ),
    ]
